theme: jekyll-theme-minimal
title: Voltaire Press
description: Writing, Poetry, and Metaphysical News

# This enables real layouts
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

